name: Test

on: [push,pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: yarn install --frozen-lockfile
      - run: yarn tsc
      - run: yarn test
